apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aventus-exercise.fullname" . }}
  labels:
    {{- include "aventus-exercise.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "aventus-exercise.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "aventus-exercise.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "aventus-exercise.serviceAccountName" . }}
      containers:
        - name: app
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
