apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aventus-exercise.postgres-fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "aventus-exercise.postgres-name" . }}
  template:
    metadata:
      labels:
        app: {{ include "aventus-exercise.postgres-name" . }}
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user | b64dec | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password | b64dec | quote }}
          ports:
            - containerPort: 5432
