version: '3.8'
services:
  web:
    build: './DEVOPS Exercise Statement 1/Dockerize_the_Backend/'
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://gelson:shadow@db/aventus_db
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: aventus_db
      POSTGRES_USER: gelson
      POSTGRES_PASSWORD: shadow
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
