fullnameOverride: ""

replicaCount: 1

postgres:
  enabled: true
  image:
    repository: postgres
    tag: 12
    pullPolicy: IfNotPresent
  user: "Z2Vsc29u"  # base64 for 'gelson'
  password: "c2hhZG93"  # base64 for 'shadow'

app:
  image:
    repository: gelsonm/aventus-app
    pullPolicy: IfNotPresent
    tag: "latest"

service:
  type: ClusterIP
  port: 80

serviceAccount:
  create: true

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: app.aventus.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []  # Fill in your TLS details if needed

pgadmin:
  enabled: true
  image:
    repository: dpage/pgadmin4
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: pgadmin.aventus.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []  # Fill in your TLS details if needed

autoscaling:
  enabled: false
